ARG PYTHON_VERSION=3.12
FROM ghcr.io/multi-py/python-quasiqueue:py${PYTHON_VERSION}-slim-LATEST

ENV MODULE_NAME=ali_backend.qq

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./ /app
