"""Add test_model

Revision ID: 1a20c870a6d1
Revises: 
Create Date: 2025-07-29 13:50:41.756160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a20c870a6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_model_id'), 'test_model', ['id'], unique=False)
    op.create_index(op.f('ix_test_model_name'), 'test_model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_model_name'), table_name='test_model')
    op.drop_index(op.f('ix_test_model_id'), table_name='test_model')
    op.drop_table('test_model')
    # ### end Alembic commands ###
