"""create initial tables

Revision ID: 446ac4cb0b1b
Revises: 4e8c10e1a071
Create Date: 2025-07-29 17:23:41.511162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446ac4cb0b1b'
down_revision = '4e8c10e1a071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
