"""Add test_model

Revision ID: 75283ffc7996
Revises: 1a20c870a6d1
Create Date: 2025-07-29 13:54:55.226669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75283ffc7996'
down_revision = '1a20c870a6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
