"""Add test_model

Revision ID: f279968ec644
Revises: 75283ffc7996
Create Date: 2025-07-29 14:02:43.934994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f279968ec644'
down_revision = '75283ffc7996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
